### ISSUE TITLE
Add async-profiler x64 to jvm image

### ISSUE THREAD

**Issue by armasanea** [lightrun-platform/koolkits#6]
Today the jvm image contains async-profiler images built for arm64: https://github.com/lightrun-platform/koolkits/blob/main/jvm/Dockerfile#L83. 
There are many workloads that run on x64 architecture so would be nice to get x64 binaries too

**Comment by pvorb** [comment]
I'm also wondering whether that might have been a mistake. Other tools target amd64 architecture.

@TomGranot Could you please verify that amd64 is the intended architecture for these tools?

**Comment by shai-almog** [comment]
Sorry about this I saw this over the weekend and I'm traveling this week so didn't get a chance to comment and it flew my mind.  @TomGranot  is on a well earned vacation (his first since joining Lightrun). Next week we should both be in the office to discuss this. 

Personally I think with the rise of ARM servers having an ARM version makes sense. Also for testing these tools on a new Mac that might also be helpful. But Tom is the expert here.

**Comment by armasanea** [comment]
While including arm originally might have been a mistake, it is useful to have a single image with tools for various architectures to avoid the need to do security scans on several images before using them inside the company. If there are plans to provide split images for each architecture let me know and I can cleanup the PR to remove arm version.

**Comment by TomGranot** [comment]
Merged in https://github.com/lightrun-platform/koolkits/pull/7, closing.

Thanks @armasanea and @pvorb! Will also push to dockerhub later on today, as CI's not yet in place to do that automatically.
